(deftheme jellybeans
  "Created 2013-02-07.")

(custom-theme-set-faces
 'jellybeans
 '(default ((t (:inherit nil :stipple nil :background "#151515" :foreground "#e8e8d3" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
 '(cursor ((t (:background "#b0d0f0"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#668799"))))
 '(minibuffer-prompt ((t (:foreground "#dddddd"))))
 '(highlight ((t (:background "#302028" :foreground "#f0a0c0" :underline t))))
 '(region ((t (:background "#404040"))))
 '(shadow ((t (:foreground "#606060"))))
 '(secondary-selection ((t (:background "#303030"))))
 '(trailing-whitespace ((t (:background "#302028"))))
 '(font-lock-builtin-face ((t (:foreground "#7697d6"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face :foreground "#808080"))))
 '(font-lock-comment-face ((t (:foreground "#888888"))))
 '(font-lock-constant-face ((t (:foreground "#cf6a4c"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#fad07a" :weight normal))))
 '(font-lock-keyword-face ((t (:weight normal :foreground "#8197bf"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face) :foreground "#8fbfdc"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#99ad6a"))))
 '(font-lock-type-face ((t (:foreground "#ffb964" :weight normal))))
 '(font-lock-variable-name-face ((t (:foreground "#c6b6fe"))))
 '(font-lock-warning-face ((t (:inherit (error) :foreground "#902020" :weight bold))))
 '(button ((t (:foreground "#0000df" :underline t))))
 '(link ((t (:foreground "#0000df" :underline t))))
 '(link-visited ((t (:inherit link :foreground "#540063"))))
 '(fringe ((t (:background "#404040"))))
 '(header-line ((default (:inherit (mode-line))) (((type tty)) (:underline t :inverse-video nil)) (((class color grayscale) (background light)) (:box nil :foreground "grey20" :background "grey90")) (((class color grayscale) (background dark)) (:box nil :foreground "grey90" :background "grey20")) (((class mono) (background light)) (:underline t :box nil :inverse-video nil :foreground "black" :background "white")) (((class mono) (background dark)) (:underline t :box nil :inverse-video nil :foreground "white" :background "black"))))
 '(tooltip ((t (:foreground "#ffffff" :background "#606060" :inherit variable-pitch))))
 '(mode-line ((t (:background "#b0b8c0" :foreground "#000000" :box (:line-width -1 :style released-button)))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold)))))

(provide-theme 'jellybeans)
